const http=require('http'),{spawn}=require('child_process'),{randomUUID,createHmac}=require('crypto'),assert=require('assert/strict');
const cwd=require('node:path').resolve(__dirname,'..'),secret='local-test-secret-not-production',sid='12345678-1234-4234-8234-123456789abc';
const slot={provider:'openai',model:'gpt-6-luna',reasoning:'low'},settings={mode:'single',primary:slot,verifier:slot,arbiter:slot,scienceGate:slot,followup:{enabled:true,model:slot,maxPerQuestion:3},arbitration:{confidenceThreshold:85},dailyLimit:10};
const tables={students:[{id:sid,name:'Test Student',campus:'Test',active:true,must_change_pin:false,class_id:'class1'}],classes:[{id:'class1',allowed_subjects:['chemistry']}],app_settings:[{id:'ai_solver',value:settings},{id:'input_guard',value:{enabled:false}}],solve_jobs:[],solve_history:[],solve_job_calls:[],api_usage:[]},storage=new Map();let modelCalls=0,quota=0;
function json(res,data,status=200){res.writeHead(status,{'Content-Type':'application/json','Content-Range':`0-0/${Array.isArray(data)?data.length:1}`});res.end(JSON.stringify(data))}
const backend=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1'),chunks=[];for await(const c of req)chunks.push(c);const bytes=Buffer.concat(chunks);let body={};try{body=JSON.parse(bytes.toString())}catch{};
 if(u.pathname==='/v1/responses'){const n=++modelCalls;await new Promise(r=>setTimeout(r,300));const data=n%2===1?{allowed:true,category:'chemistry',confidence:100,reason:'science question',topic:'chemistry',keywords:[]}:{answer:'8 g',explanation:'Background completed correctly.',options:'',annotations:[]};const text=JSON.stringify(data);return json(res,{id:'response-'+n,object:'response',created_at:Date.now()/1000,status:'completed',model:'gpt-6-luna',output_text:text,output:[{id:'message',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text,annotations:[]}]}],usage:{input_tokens:100,output_tokens:50,total_tokens:150}})}
 if(u.pathname.startsWith('/storage/v1/object/')){let path=decodeURIComponent(u.pathname.replace('/storage/v1/object/','').replace(/^authenticated\//,''));if(req.method==='POST'){storage.set(path,bytes);return json(res,{Key:path})}if(req.method==='GET'){const v=storage.get(path);if(!v)return json(res,{error:'not found'},404);res.end(v);return}if(req.method==='DELETE'){for(const p of body.prefixes||[])storage.delete(path+'/'+p);return json(res,[])} }
 if(u.pathname.startsWith('/storage/v1/object/sign/'))return json(res,{signedURL:'/mock-image'});
 if(u.pathname.startsWith('/rest/v1/rpc/')){const name=u.pathname.split('/').pop();if(name==='consume_auth_rate_limit')return json(res,{allowed:true});const job=tables.solve_jobs.find(x=>x.id===body.p_job);if(name==='reserve_solve_job_quota'){if(job.quota_state!=='reserved'){quota++;job.quota_state='reserved';job.quota_count=quota}return json(res,{allowed:true,count:job.quota_count})}if(name==='finish_solve_job'){if(!['succeeded','failed'].includes(job.status)){job.status=body.p_status<400?'succeeded':'failed';job.stage=job.status==='succeeded'?'complete':'failed';job.result=body.p_result;job.history_id=body.p_history;job.http_status=body.p_status;if(job.status==='failed'&&job.quota_state==='reserved')quota--;job.quota_state=job.status==='failed'?'released':'committed'}return json(res,null)}return json(res,[])}
 if(u.pathname.startsWith('/rest/v1/')){const table=u.pathname.split('/').pop();tables[table]??=[];const match=row=>[...u.searchParams].every(([k,v])=>{if(['select','order','limit','offset','on_conflict'].includes(k))return true;if(v.startsWith('eq.'))return String(row[k])===v.slice(3);if(v.startsWith('in.'))return v.slice(4,-1).split(',').includes(String(row[k]));if(v==='is.null')return row[k]==null;return true});let rows=tables[table].filter(match);
 if(req.method==='POST'){const row={...body};if(table==='solve_jobs'&&tables[table].some(x=>x.student_id===row.student_id&&(x.client_key===row.client_key||['uploading','queued','running'].includes(x.status))))return json(res,{code:'23505',message:'duplicate'},409);if(table==='solve_job_calls'&&tables[table].some(x=>x.job_id===row.job_id&&x.phase===row.phase))return json(res,{code:'23505',message:'duplicate'},409);row.id??=randomUUID();row.created_at??=new Date().toISOString();row.updated_at??=row.created_at;if(table==='solve_jobs'){row.status??='uploading';row.stage??='uploading';row.quota_state??='none'}tables[table].push(row);rows=[row];}
 if(req.method==='PATCH'){for(const row of rows)Object.assign(row,body)}
 if(u.searchParams.has('limit'))rows=rows.slice(0,Number(u.searchParams.get('limit')));
 return json(res,String(req.headers.accept||'').includes('application/vnd.pgrst.object')?rows[0]||null:rows)}
 console.log('UNHANDLED',req.method,u.pathname);return json(res,{});
 }catch(e){console.error(e);json(res,{error:e.message},500)}});
(async()=>{await new Promise(r=>backend.listen(3050,'127.0.0.1',r));const server=spawn(process.execPath,[cwd+'/node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3024'],{cwd,env:{...process.env,SUPABASE_URL:'http://127.0.0.1:3050',SUPABASE_SECRET_KEY:'test-key',SESSION_SECRET:secret,OPENAI_API_KEY:'test-key',OPENAI_BASE_URL:'http://127.0.0.1:3050/v1',WORKFLOW_TARGET_WORLD:'local',WORKFLOW_LOCAL_BASE_URL:'http://127.0.0.1:3024',WORKFLOW_LOCAL_DATA_DIR:'/tmp/workflow-e2e-'+randomUUID()},stdio:'pipe'});try{
 await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{const s=b.toString();process.stdout.write(b);if(s.includes('Ready'))resolve()});server.stderr.on('data',b=>process.stderr.write(b));server.on('exit',()=>reject(Error('server exited')));setTimeout(()=>reject(Error('server timeout')),15000).unref()});
 const encoded=Buffer.from(JSON.stringify({studentId:sid,campus:'Test',name:'Test Student',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),signature=createHmac('sha256',secret).update(encoded).digest('base64url'),headers={'Content-Type':'application/json',Cookie:`hh_science_session=${encoded}.${signature}`};
 const payload={clientKey:randomUUID(),background:true,subject:'chemistry',referenceAnswer:'8',images:['data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==']};
 const r=await fetch('http://127.0.0.1:3024/api/solve',{method:'POST',headers,body:JSON.stringify(payload)});const d=await r.json();console.log('SUBMIT',r.status,d);assert.equal(r.status,202);assert.ok(d.job.id);
 const duplicate=await fetch('http://127.0.0.1:3024/api/solve',{method:'POST',headers,body:JSON.stringify(payload)});assert.equal((await duplicate.json()).job.id,d.job.id);assert.equal(tables.solve_jobs.length,1);
 // No page or polling connection stays open while work is executing.
 await new Promise(r=>setTimeout(r,3000));
 let job;for(let i=0;i<20;i++){const r=await fetch('http://127.0.0.1:3024/api/solve-jobs?id='+d.job.id,{headers});const result=await r.json();job=result.job;console.log('POLL',job?.status,job?.stage,result.error||'');if(['failed','succeeded'].includes(job?.status))break;await new Promise(r=>setTimeout(r,500))}
 assert.equal(job?.status,'succeeded');assert.equal(job.result.answer,'8 g');assert.equal(modelCalls,2);assert.equal(quota,1);assert.equal(tables.solve_history.length,1);
 const restored=await fetch('http://127.0.0.1:3024/api/solve-jobs',{headers});assert.equal((await restored.json()).job.id,d.job.id);
 const again=await fetch('http://127.0.0.1:3024/api/solve',{method:'POST',headers,body:JSON.stringify(payload)});assert.equal((await again.json()).job.id,d.job.id);assert.equal(modelCalls,2);
 const otherId=randomUUID();tables.students.push({...tables.students[0],id:otherId});
 const otherEncoded=Buffer.from(JSON.stringify({studentId:otherId,campus:'Test',name:'Other',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');const otherSig=createHmac('sha256',secret).update(otherEncoded).digest('base64url');
 const cross=await fetch('http://127.0.0.1:3024/api/solve-jobs?id='+d.job.id,{headers:{Cookie:`hh_science_session=${otherEncoded}.${otherSig}`}});assert.equal((await cross.json()).job,null);
 const unauth=await fetch('http://127.0.0.1:3024/api/solve-jobs?id='+d.job.id);assert.equal(unauth.status,401);
 console.log('PASS: actual Workflow local execution after submission returns, durable result/history, restored task, idempotent submission, one quota reservation');
 }catch(e){console.error(e);console.log('JOBS',JSON.stringify(tables.solve_jobs.map(({settings,...j})=>j)));process.exitCode=1}finally{server.kill('SIGTERM');backend.closeAllConnections();backend.close()}})();
