"use client";
import {useState} from 'react';
type Draft={key:string;file:File;title:string;subject:string;keywords:string;description:string;status:string};
const subjects=[['physics','物理'],['chemistry','化學'],['biology','生物'],['earth','地科']];
export async function suggestImage(file:File){const form=new FormData();form.set('file',file);const r=await fetch('/api/admin/teaching-images/suggest',{method:'POST',body:form}),d=await r.json();if(!r.ok)throw Error(d.error);return d;}
export function ImageLibraryBatch({onChanged}:{onChanged:()=>Promise<void>}){
 const [drafts,setDrafts]=useState<Draft[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const patch=(key:string,value:Partial<Draft>)=>setDrafts(rows=>rows.map(r=>r.key===key?{...r,...value}:r));
 async function suggest(row:Draft){setBusy(true);setError('');try{const d=await suggestImage(row.file);patch(row.key,{title:d.title,subject:d.subject,keywords:d.keywords.join(', '),description:d.description,status:'建議已填入，請確認內容後再上傳。'});}catch(e){setError(e instanceof Error?e.message:'建議失敗')}finally{setBusy(false)}}
 async function upload(){setBusy(true);setError('');let succeeded=0;for(const row of drafts.filter(r=>r.status!=='已上傳')){if(!row.title.trim()||!row.keywords.trim()||!row.description.trim()){patch(row.key,{status:'請填寫標題、關鍵字與說明。'});continue;}try{const form=new FormData();form.set('file',row.file);form.set('title',row.title);form.set('subject',row.subject);form.set('keywords',row.keywords);form.set('description',row.description);form.set('enabled','false');const r=await fetch('/api/admin/teaching-images',{method:'POST',body:form}),d=await r.json();if(!r.ok)throw Error(d.error);patch(row.key,{status:'已上傳'});succeeded++;}catch(e){patch(row.key,{status:e instanceof Error?e.message:'上傳失敗，請重試。'});}}if(succeeded)await onChanged();setBusy(false);}
 return <details className="hh-card admin-panel"><summary>批次上傳講義圖片</summary><p className="hh-muted">一次最多 10 張，每張 3 MB。上傳後預設停用，確認後可在圖庫批次啟用。AI 建議會產生少量 API 費用。</p><fieldset disabled={busy} style={{border:0,padding:0,minWidth:0}}><input aria-label="批次選擇教材圖片" type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length>10||files.some(f=>f.size>3*1024*1024)){setError('每批最多 10 張，每張需小於 3 MB。');return;}setError('');setDrafts(files.map(file=>({key:crypto.randomUUID(),file,title:file.name.replace(/\.[^.]+$/,''),subject:'chemistry',keywords:'',description:'',status:''})));}}/>{drafts.map(row=><div key={row.key} className="upgrade-compact image-library-form"><strong>{row.file.name}</strong><label>標題<input className="hh-input" value={row.title} maxLength={80} onChange={e=>patch(row.key,{title:e.target.value})} disabled={row.status==='已上傳'}/></label><label>科目<select className="hh-select" value={row.subject} onChange={e=>patch(row.key,{subject:e.target.value})}>{subjects.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>關鍵字<input className="hh-input" value={row.keywords} onChange={e=>patch(row.key,{keywords:e.target.value})}/></label><label>使用說明<textarea className="hh-input" rows={3} value={row.description} onChange={e=>patch(row.key,{description:e.target.value})}/></label><button className="hh-button-secondary" disabled={row.status==='已上傳'} onClick={()=>void suggest(row)}>AI 建議標籤與說明</button><p aria-live="polite">{row.status}</p></div>)}{error&&<p role="alert">{error}</p>}{drafts.length>0&&<div className="upgrade-actions"><button className="hh-button-primary" onClick={()=>void upload()}>{busy?'處理中…':'上傳尚未完成的圖片'}</button><button className="hh-button-secondary" onClick={()=>setDrafts([])}>清空清單</button></div>}</fieldset></details>;
}
export function ImageReferences({id}:{id:string}){
 const [data,setData]=useState<{count:number;items:Array<{id:string;historyId:string;name:string;kind:string;createdAt:string}>}|null>(null),[error,setError]=useState('');
 async function load(){try{const r=await fetch(`/api/admin/teaching-images/${id}/references`),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'讀取失敗')}}
 return <details className="upgrade-compact" onToggle={e=>{if(e.currentTarget.open&&!data)void load();}}><summary>查看引用紀錄</summary>{error?<p>{error}</p>:data?<><p>管理範圍內共引用 {data.count} 次，顯示最近 20 筆。</p><ul className="upgrade-work-items">{data.items.map(i=><li key={i.id}><a href={`/admin?section=siteQuestions&question=${i.historyId}&sq_range=all`}>{i.name} · {i.kind}<small>{new Date(i.createdAt).toLocaleString('zh-TW')}</small></a></li>)}</ul></>:<p>讀取中…</p>}</details>;
}
