'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import katex from 'katex';
import ChemicalStructureView from '@/components/chemical-structure';
import ScienceDiagramView from '@/components/science-diagram';
import {CRITERIA,CRITERIA_LABELS,OPTIONS,calculateScore,type Ratings,type Criterion} from '@/lib/comparison/rubric';
import {reserveTwd,type ComparisonConfig} from '@/lib/comparison/config';
import type {AIModelDefinition} from '@/lib/ai-models';
import type {ScienceDiagram,ChemicalStructure} from '@/lib/ai/types';
import './model-comparison.css';
const SUBJECTS:Record<string,string>={physics:'物理',chemistry:'化學',biology:'生物',earth:'地科',auto:'自動判斷'};
const sourceName=(v:string)=>v==='historical'?'歷史重解':v==='auto'?'自動抽樣':'手動挑題';
const STATUS:Record<string,string>={queued:'待派工',running:'解題中',ready:'待評閱',failed:'比較未完成',interrupted:'工作中斷・未重送'};
const ENDPOINT='/api/admin/model-comparison';
async function api(query:string,body?:unknown,signal?:AbortSignal){const r=await fetch(ENDPOINT+query,{cache:'no-store',signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'操作失敗');return d;}
export function AddComparisonButton({historyId}:{historyId:string}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <span className="mc-add"><button type="button" className="hh-button-secondary" disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{await api('',{action:'manual',historyId});setMessage('已加入比較，請至 AI 模型中心 → 模型比較查看。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>{busy?'加入中…':'加入雙模型比較（額外計費）'}</button><span role="status">{message}</span></span>;
}
type Row={id:string;createdAt:string;subject:string;source:string;version:string;status:string;reviewed:boolean};
type Answer={answer:string;explanation:string;options:string;diagram:ScienceDiagram|null;chemicalStructure?:ChemicalStructure|null;model?:string;latencyMs?:number;costUsd?:number;reused?:boolean;ratings?:Ratings;score?:ReturnType<typeof calculateScore>};
type Detail={id:string;subject:string;source:string;status:string;createdAt:string;images:string[];note:string;referenceAnswer:string;referenceMode:string;answers:Answer[];reviewed:boolean;review:{preference:string;note:string}|null};
type Settings={version:string|null;config:ComparisonConfig;models:AIModelDefinition[];classes:{id:string;name:string}[];canEdit:boolean};
function FormulaText({text}:{text:string}){
 return <div className="mc-text">{text.split(/(\$\$[\s\S]*?\$\$|\$[^$\n]+\$|\\\[[\s\S]*?\\\]|\\\([\s\S]*?\\\))/g).map((part,i)=>{
 const display=part.startsWith('$$')||part.startsWith('\\['),inline=part.startsWith('$')||part.startsWith('\\(');
 if(!display&&!inline)return <span key={i}>{part}</span>;
 const n=display||part.startsWith('\\(')?2:1;
 try{return <span key={i} dangerouslySetInnerHTML={{__html:katex.renderToString(part.slice(n,-n),{displayMode:display,throwOnError:false,trust:context=>context.command==='\\htmlData',maxExpand:500})}}/>;}catch{return <span key={i}>{part}</span>;}
 })}</div>;
}
function Review({data,onSaved}:{data:Detail;onSaved:()=>Promise<void>}){
 const [ratings,setRatings]=useState<Partial<Ratings>[]>(data.answers.map(a=>a.ratings||{}));
 const [preference,setPreference]=useState(data.review?.preference||''),[note,setNote]=useState(data.review?.note||'');
 const [side,setSide]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const locked=data.reviewed||data.status!=='ready';
 return <div className="mc-stack"><section className="mc-panel"><div className="mc-heading"><h3>{SUBJECTS[data.subject]||'自然科'} · {sourceName(data.source)}</h3><span>{data.reviewed?'已評閱':STATUS[data.status]}</span></div><div className="mc-images">{data.images.map((url,i)=><a key={i} href={url} target="_blank" rel="noreferrer"><img src={url} alt={`原始題目圖片 ${i+1}`} loading="lazy"/></a>)}</div>{data.note&&<p>補充：{data.note}</p>}<p>參考答案：{data.referenceAnswer||'未提供'} · {data.referenceMode==='hidden'?'解題時未提供給模型':'解題時同步提供給兩模型'}</p><details><summary>評分與綜合評等規則</summary><p>答案 45%、推導 35%、辨識 10%、表達 10%。A ≥90、B ≥80、C ≥60、D &lt;60。答案錯誤或重大觀念錯誤直接 D；部分正確或辨識有誤最高 C。無法判定不計綜合分數。送出後鎖定，避免揭曉後修改盲測結果。</p></details></section>
 <div className="mc-mobile-tabs">{['回答甲','回答乙'].map((name,i)=><button key={name} type="button" className="hh-button-secondary" aria-pressed={side===i} onClick={()=>setSide(i)}>{name}</button>)}</div>
 <div className="mc-columns">{data.answers.map((a,i)=>{const complete=CRITERIA.every(k=>ratings[i][k]);const score=complete?calculateScore(ratings[i] as Ratings):null;return <section key={i} className={`mc-panel ${side!==i?'mc-mobile-hidden':''}`}><h3>回答{['甲','乙'][i]} {a.model&&<small> · {a.model}</small>}</h3>{a.model&&<p className="mc-muted">{a.reused?'沿用當時解答 · 未再次計費 · ':''}{a.latencyMs!==undefined?`${(a.latencyMs/1000).toFixed(1)} 秒`:'—'} · {a.costUsd!==undefined?`US$ ${a.costUsd.toFixed(5)}`:'費用待查'}</p>}
 <h4>答案</h4><FormulaText text={a.answer||'尚未取得完整答案'}/><h4>觀念與推導</h4><FormulaText text={a.explanation}/>{a.options&&<><h4>選項分析</h4><FormulaText text={a.options}/></>}{a.diagram&&<ScienceDiagramView diagram={a.diagram}/>}{a.chemicalStructure&&<ChemicalStructureView structure={a.chemicalStructure}/>}
 <fieldset disabled={locked||busy} className="mc-ratings"><legend>老師評分</legend>{CRITERIA.map(k=><label key={k}>{CRITERIA_LABELS[k]}<select className="hh-select" value={ratings[i][k]||''} onChange={e=>setRatings(old=>old.map((v,index)=>index===i?{...v,[k]:e.target.value}:v))}><option value="">請選擇</option>{OPTIONS[k].filter(([value])=>!(k==='image'&&data.images.length>0&&value==='na')).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>)}</fieldset>
 <div className="mc-score" aria-live="polite"><strong>{score?.score!=null?score.score.toFixed(1):'—'} <small>/ 100</small></strong><span>{score?.grade||'待評分'}</span></div>{score?.reason&&<p className="mc-muted">{score.reason}</p>}</section>})}</div>
 <section className="mc-panel"><fieldset disabled={locked||busy}><label>整體偏好（不計入綜合分數）<select className="hh-select" value={preference} onChange={e=>setPreference(e.target.value)}><option value="">請選擇</option><option value="left">回答甲較好</option><option value="right">回答乙較好</option><option value="tie">相當</option><option value="neither">兩者皆不合格</option></select></label><label>評閱備註<textarea className="hh-input" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label></fieldset>{!data.reviewed&&<button className="hh-button-primary" disabled={locked||busy} onClick={async()=>{setBusy(true);setError('');try{await api('',{action:'review',id:data.id,left:ratings[0],right:ratings[1],preference,note});await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'儲存中…':'送出評分並揭曉模型'}</button>}<p role="alert">{error}</p>{data.status!=='ready'&&<p>兩模型都完成後才能評閱；失敗的呼叫不自動重送。</p>}</section></div>;
}
export default function ModelComparison(){
 const [tab,setTab]=useState<'list'|'settings'|'stats'|'history'>('list'),[settings,setSettings]=useState<Settings|null>(null),[config,setConfig]=useState<ComparisonConfig|null>(null);
 const [batches,setBatches]=useState<any[]>([]);
 const [items,setItems]=useState<Row[]>([]),[hasMore,setHasMore]=useState(false),[page,setPage]=useState(0),[subject,setSubject]=useState(''),[source,setSource]=useState(''),[currentOnly,setCurrentOnly]=useState(false);
 const [selected,setSelected]=useState<Detail|null>(null),[stats,setStats]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const requestSequence=useRef(0);
 const load=useCallback(async()=>{
  const seq=++requestSequence.current;setLoading(true);setError('');
  try{const params=new URLSearchParams({mode:tab==='stats'?'stats':'list',page:String(page)});if(subject)params.set('subject',subject);if(tab==='history')params.set('source','historical');else if(source)params.set('source',source);if(tab!=='history'&&currentOnly&&settings?.version)params.set('version',settings.version);
   const d=await api('?'+params);if(seq!==requestSequence.current)return;if(tab==='stats')setStats(d.groups);else{setItems(d.items);setHasMore(d.hasMore);}
  }catch(e){if(seq===requestSequence.current)setError((e as Error).message);}finally{if(seq===requestSequence.current)setLoading(false);}
 },[tab,page,subject,source,currentOnly,settings?.version]);
 useEffect(()=>{const controller=new AbortController();api('?mode=settings',undefined,controller.signal).then(d=>{setSettings(d);setConfig(d.config);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{if(tab!=='settings')void load();return()=>{requestSequence.current++;};},[load,tab]);
 useEffect(()=>{if(tab!=='history')return;let alive=true;const refresh=()=>api('?mode=batches').then(d=>{if(alive)setBatches(d.batches);}).catch(e=>{if(alive)setError(e.message);});void refresh();const timer=setInterval(refresh,10000);return()=>{alive=false;clearInterval(timer);};},[tab]);
 async function batchAction(id:string,action:string){setBusy(true);setError('');try{await api('',{id,action});setBatches((await api('?mode=batches')).batches);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function open(id:string){setLoading(true);setError('');try{setSelected(await api('?mode=detail&id='+id));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 function field<K extends keyof ComparisonConfig>(key:K,value:ComparisonConfig[K]){setConfig(c=>c?{...c,[key]:value}:c);}
 return <div className="mc-root mc-stack"><div className="mc-heading"><div><h2>模型比較</h2><p className="mc-muted">獨立解答、盲測評閱，累積你自己的模型品質資料。</p></div><span>{settings?.config.enabled?`抽樣 ${settings.config.percentage}%`:'自動抽樣關閉'}</span></div>
 <nav className="mc-tabs" aria-label="比較功能">{([['list','題目評閱'],['history','歷史重解'],['settings','比較設定'],['stats','比較結果']] as const).map(([key,title])=><button className={tab===key?'hh-button-primary':'hh-button-secondary'} key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setSelected(null);setPage(0);setMessage('');}}>{title}</button>)}</nav>
 {error&&<p role="alert" className="mc-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {tab!=='settings'&&!selected&&<div className="mc-filters"><label>科目<select className="hh-select" value={subject} onChange={e=>{setSubject(e.target.value);setPage(0);}}><option value="">全部</option>{Object.entries(SUBJECTS).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>來源<select className="hh-select" disabled={tab==='history'} value={tab==='history'?'historical':source} onChange={e=>{setSource(e.target.value);setPage(0);}}><option value="">全部（分開統計）</option><option value="auto">自動抽樣</option><option value="manual">手動挑題</option><option value="historical">歷史重解</option></select></label><label><input type="checkbox" disabled={tab==='history'} checked={tab==='history'?false:currentOnly} onChange={e=>{setCurrentOnly(e.target.checked);setPage(0);}}/>只看目前設定版本</label><button className="hh-button-secondary" disabled={loading} onClick={()=>void load()}>重新整理</button></div>}
 {tab==='history'&&!selected&&<><p className="mc-muted">保留原解答，只由 GPT-6 Luna 重新解題。原解答可能使用不同規則或經過複核，這些結果獨立統計。完成一題就能開始評閱。</p>{batches.map(batch=><section key={batch.id} className="mc-panel"><h3>{batch.label}</h3><p>{({queued:'準備執行',running:'批次執行中',paused:'已暫停',completed:'批次處理完成'} as Record<string,string>)[batch.status]} · 共 {batch.progress.total} 題</p><div className="mc-stat-grid"><div>已完成<strong>{batch.progress.succeeded}</strong></div><div>尚待執行<strong>{batch.progress.queued}</strong></div><div>失敗／缺圖<strong>{batch.progress.failed}</strong></div></div><p>執行中 {batch.progress.running} · 已評閱 {batch.progress.reviewed} · 已知新增費用 US$ {Number(batch.progress.costUsd).toFixed(5)}</p><p>{batch.reason}</p>{settings?.canEdit&&<div className="mc-actions">{batch.status==='running'&&<button className="hh-button-secondary" disabled={busy} onClick={()=>void batchAction(batch.id,'pauseBatch')}>暫停後續題目</button>}{['queued','paused'].includes(batch.status)&&<button className="hh-button-secondary" disabled={busy} onClick={()=>void batchAction(batch.id,'resumeBatch')}>繼續未執行題目</button>}</div>}</section>)}</>}
 {loading&&<p role="status">載入中…</p>}
 {(tab==='list'||tab==='history')&&(selected?<><button className="hh-button-secondary" onClick={()=>{setSelected(null);void load();}}>← 返回比較題目</button><Review key={selected.id+String(selected.reviewed)} data={selected} onSaved={async()=>{await open(selected.id);}}/></>:<><p className="mc-muted">手動比較：到「全站題目」點入一題，按「加入雙模型比較」。每題額外呼叫兩模型，不扣學生額度。</p>{!loading&&items.length===0&&<div className="mc-panel">尚無比較題目。請先儲存比較設定，再開啟抽樣或手動加入題目。</div>}{items.map(row=><div key={row.id} className="mc-panel mc-heading"><div><strong>{SUBJECTS[row.subject]||'自然科'}</strong><p>{new Date(row.createdAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})} · {sourceName(row.source)} · {row.reviewed?'已評閱':STATUS[row.status]}</p></div><div className="mc-actions"><button className="hh-button-secondary" disabled={loading} onClick={()=>void open(row.id)}>{row.reviewed?'查看結果':row.status==='ready'?'開始盲測':'查看狀態'}</button>{row.status==='queued'&&settings?.canEdit&&<button className="hh-button-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('',{action:'dispatch',id:row.id});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>恢復未派工任務</button>}</div></div>)}<div className="mc-actions"><button className="hh-button-secondary" disabled={page===0||loading} onClick={()=>setPage(v=>v-1)}>上一頁</button><span>{page+1}</span><button className="hh-button-secondary" disabled={!hasMore||loading} onClick={()=>setPage(v=>v+1)}>下一頁</button></div></>)}
 {tab==='settings'&&config&&settings&&<section className="mc-panel"><fieldset disabled={!settings.canEdit||busy}><label className="mc-check"><input type="checkbox" checked={config.enabled} onChange={e=>field('enabled',e.target.checked)}/>啟用自動抽樣</label><div className="mc-columns">{(['a','b'] as const).map(slot=><div key={slot}><label>模型 {slot.toUpperCase()}<select className="hh-select" value={config[slot].model} onChange={e=>{const m=settings.models.find(m=>m.id===e.target.value)!;field(slot,{model:e.target.value as ComparisonConfig['a']['model'],reasoning:m.reasoningLevels.includes('medium')?'medium':m.reasoningLevels[0]});}}>{settings.models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>推理強度<select className="hh-select" value={config[slot].reasoning} onChange={e=>field(slot,{...config[slot],reasoning:e.target.value as ComparisonConfig['a']['reasoning']})}>{settings.models.find(m=>m.id===config[slot].model)?.reasoningLevels.map(level=><option key={level}>{level}</option>)}</select></label></div>)}</div>
 <label>自動抽樣比例：{config.percentage}%<div className="mc-actions"><input aria-label="抽樣比例滑桿" type="range" min={0} max={100} step={1} value={config.percentage} onChange={e=>field('percentage',Number(e.target.value))}/><input aria-label="抽樣比例數值" className="hh-input mc-number" type="number" min={0} max={100} step={1} value={config.percentage} onChange={e=>field('percentage',Number(e.target.value))}/></div></label><p className="mc-muted">0% 停止自動抽樣；100% 仍受每日題數與預估預算限制。實際比例有隨機波動。</p>
 <div className="mc-columns"><label>每日最多比較題数<input className="hh-input" type="number" min={1} max={1000} value={config.dailyLimit} onChange={e=>field('dailyLimit',Number(e.target.value))}/></label><label>每日預估比較預算（NT$）<input className="hh-input" type="number" min={1} max={100000} value={config.dailyBudgetTwd} onChange={e=>field('dailyBudgetTwd',Number(e.target.value))}/></label><label>試算匯率（1 美元＝NT$）<input className="hh-input" type="number" min={1} max={100} step={0.1} value={config.usdTwd} onChange={e=>field('usdTwd',Number(e.target.value))}/></label><label>參考答案<select className="hh-select" value={config.referenceMode} onChange={e=>field('referenceMode',e.target.value as ComparisonConfig['referenceMode'])}><option value="provided">同步提供兩模型</option><option value="hidden">不提供兩模型</option></select></label></div>
 <p className="mc-muted">每題暫留約 NT$ {Number.isFinite(reserveTwd(config))?reserveTwd(config).toFixed(2):'—'} 預算，成功後依 token 用量結算；失敗或不明費用保留額度。這是估算停送門檻，並非供應商帳單的硬上限。每日以台北時間重設。</p><div className="mc-actions">{Object.entries(SUBJECTS).map(([v,t])=><label className="mc-check" key={v}><input type="checkbox" checked={config.subjects.includes(v)} onChange={e=>field('subjects',e.target.checked?[...config.subjects,v]:config.subjects.filter(s=>s!==v))}/>{t}</label>)}</div>
 <details><summary>指定班級（未勾選＝所有班級）</summary>{settings.classes.map(c=><label className="mc-check" key={c.id}><input type="checkbox" checked={config.classIds.includes(c.id)} onChange={e=>field('classIds',e.target.checked?[...config.classIds,c.id]:config.classIds.filter(id=>id!==c.id))}/>{c.name}</label>)}</details>
 <p>盲測預設啟用。修改設定會建立新版本，既有評分與比較结果保留。</p><button className="hh-button-primary" onClick={async()=>{setBusy(true);setError('');setMessage('');try{await api('',{action:'settings',version:settings.version,config});const d=await api('?mode=settings');setSettings(d);setConfig(d.config);setMessage('比較設定已儲存，適用於之後的新題。');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'儲存中…':'儲存比較設定'}</button></fieldset>{!settings.canEdit&&<p>只有總管理員可變更設定。</p>}</section>}
 {tab==='stats'&&<><p className="mc-muted">按實驗版本、來源、科目與參考答案模式分組。正確率只計兩邊皆可判定的同批題目；平均綜合分數只計兩邊皆有綜合分數的同批題目。</p>{!loading&&!stats.length&&<div className="mc-panel">尚無統計資料，完成比較與老師評閱後會顯示。</div>}{stats.map(g=><section className="mc-panel" key={g.key}><h3>{g.model} · {SUBJECTS[g.subject]||'自然科'}</h3><p className="mc-muted">版本 {g.version.slice(0,8)} · {sourceName(g.source)} · {g.referenceMode==='hidden'?'未提供答案':'隨題提供答案'} · 推理 {g.reasoning}</p><div className="mc-stat-grid"><div>配對正確率<strong>{g.accuracy===null?'—':(g.accuracy*100).toFixed(1)+'%'}</strong><small>{g.correct} / {g.paired} 題</small></div><div>綜合分數<strong>{g.averageScore===null?'—':g.averageScore.toFixed(1)}</strong><small>{g.scored} 題配對評分</small></div><div>成功完成<strong>{g.success} / {g.total}</strong><small>已評閱 {g.reviewed} 題</small></div></div><p>重大錯誤 {g.majorErrors} / {g.reviewed} 次評閱 · 偏好勝出 {g.wins} · 平手 {g.ties} · 皆不合格 {g.neither}</p><p>平均 {g.averageMs===null?'—':(g.averageMs/1000).toFixed(1)} 秒 · P95 {g.p95Ms===null?'—':(g.p95Ms/1000).toFixed(1)} 秒<br/>已知費用 US$ {g.costUsd.toFixed(5)} · 費用待確認／待執行 {g.unknownCost} 次</p></section>)}</>}
 </div>;
}
