"use client";
import {useEffect,useState} from "react";
export type ModelConfiguration={mode:"single"|"multi";primary:Slot;verifier:Slot;arbiter:Slot;scienceGate:Slot;arbitration:{confidenceThreshold:number};followup:{enabled:boolean;model:Slot;maxPerQuestion:number};dailyLimit:number};
type Slot={provider:"openai"|"gemini";model:string;reasoning:string};
export function ModelConfigurationTools({settings,onChange,saving}:{settings:ModelConfiguration;onChange:(value:ModelConfiguration)=>void;saving:boolean}){
 const [previous,setPrevious]=useState<ModelConfiguration|null>(null),[saved,setSaved]=useState<ModelConfiguration|null>(null),[busy,setBusy]=useState(false),[messages,setMessages]=useState<string[]>([]);
 useEffect(()=>{if(saving)return;let alive=true;fetch('/api/admin/ai-settings').then(r=>r.json()).then(d=>{if(alive){setPrevious(d.previous||null);setSaved(d.settings||null);}}).catch(()=>{});return()=>{alive=false;};},[saving]);
 const slot=(model:string,reasoning:string):Slot=>({provider:'openai',model,reasoning});
 function preset(kind:string){onChange({...settings,mode:kind==='fast'?'single':'multi',primary:slot(kind==='fast'?'gpt-6-luna':kind==='balanced'?'gpt-6-sol':'gpt-6-astra',kind==='fast'?'low':kind==='balanced'?'medium':'high'),verifier:slot(kind==='precise'?'gpt-6-sol':'gpt-6-luna',kind==='precise'?'medium':'low'),arbiter:slot('gpt-6-astra','high')});setMessages(['已套用至草稿。請先測試，再按下方「儲存」讓全站生效。']);}
 async function test(){setBusy(true);setMessages([]);const roles=[settings.scienceGate,settings.primary,...(settings.mode==='multi'?[settings.verifier,settings.arbiter]:[]),...(settings.followup.enabled?[settings.followup.model]:[])];const unique=roles.filter((s,i)=>roles.findIndex(x=>x.model===s.model&&x.reasoning===s.reasoning)===i);for(const s of unique){setMessages(m=>[...m,`${s.model}（${s.reasoning}）測試中…`]);try{const r=await fetch('/api/admin/model-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)}),d=await r.json();setMessages(m=>[...m.slice(0,-1),`${s.model}：${r.ok?d.message:d.error}${r.ok?`（${(d.elapsedMs/1000).toFixed(1)} 秒，US$${Number(d.estimatedCostUsd||0).toFixed(5)}）`:''}`]);}catch{setMessages(m=>[...m.slice(0,-1),`${s.model}：連線失敗，請稍後再試。`]);}}setBusy(false);}
 return <section className="hh-card admin-panel"><div className="admin-panel-header"><div><span className="admin-eyebrow">MODEL CONFIGURATION</span><h2>模型配置與測試</h2><p className="hh-muted">快速使用單模型；均衡與精準會啟用驗算及爭議仲裁。每日額度、追問及圖片檢查設定保留。</p></div></div><div className="upgrade-actions"><button className="hh-button-secondary" onClick={()=>preset('fast')} disabled={busy}>快速配置</button><button className="hh-button-secondary" onClick={()=>preset('balanced')} disabled={busy}>均衡配置</button><button className="hh-button-secondary" onClick={()=>preset('precise')} disabled={busy}>精準配置</button></div><p className="hh-muted">{saved&&JSON.stringify(saved)!==JSON.stringify(settings)?'有尚未儲存的設定':'目前顯示已儲存設定'}。測試會發出少量 API 請求並產生實際費用。</p><div className="upgrade-actions"><button className="hh-button-primary" disabled={busy} onClick={test}>{busy?'正在逐一測試…':'測試目前選用模型'}</button><button className="hh-button-secondary" disabled={!previous||busy} onClick={()=>{if(previous){onChange(previous);setMessages(['已載入上一版設定，按「儲存」後才會還原全站設定。']);}}}>載入上一版</button><button className="hh-button-secondary" disabled={!saved||busy} onClick={()=>{if(saved)onChange(saved);}}>放棄草稿</button></div><div aria-live="polite">{messages.map((m,i)=><p className="hh-muted" key={i}>{m}</p>)}</div></section>;
}
