"use client";
import { useEffect,useState } from 'react';
import ScienceDiagramView from '@/components/science-diagram';
import { normalizeScienceDiagram } from '@/lib/science/diagram-engine';
type Item={id:string;title:string;subject:string;description:string;keywords:string[];enabled:boolean};
const subjects=[['physics','物理'],['chemistry','化學'],['biology','生物'],['earth','地科']];
const examples=[
 {title:'受力圖',template:{kind:'force',object:'物體',forces:[{label:'N',angle:90,magnitude:10},{label:'mg',angle:270,magnitude:10}]}},
 {title:'表格',template:{kind:'table',headers:['物理量','數值'],rows:[['質量','2 kg'],['加速度','3 m/s²']]}},
 {title:'九宮格',template:{kind:'grid',rows:3,columns:3,cells:[{row:0,column:0,text:'A'}]}},
 {title:'速度—時間圖',template:{kind:'plot',xRange:[0,4],yRange:[0,8],xLabel:'t (s)',yLabel:'v (m/s)',points:[{x:0,y:0},{x:4,y:8}]}},
 ...[['filtration','過濾'],['titration','滴定'],['distillation','蒸餾']].map(([scene,title])=>({title,template:{kind:'apparatus',scene}}))
];
export default function TeachingImageLibrary({canEdit}:{canEdit:boolean}){
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [title,setTitle]=useState(''),[subject,setSubject]=useState('chemistry'),[keywords,setKeywords]=useState(''),[description,setDescription]=useState(''),[enabled,setEnabled]=useState(false),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[editing,setEditing]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[sample,setSample]=useState(0),[fileKey,setFileKey]=useState(0);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/teaching-images',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.items||[]);}catch(e){setError(e instanceof Error?e.message:'讀取失敗。')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 function reset(){setTitle('');setKeywords('');setDescription('');setEnabled(false);setFile(null);setEditing(null);setFileKey(k=>k+1)}
 async function mutate(body:Record<string,unknown>){const r=await fetch('/api/admin/teaching-images',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error)}
 async function action(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{await mutate(body);await load();setNotice('圖庫已更新。')}catch(e){setError(e instanceof Error?e.message:'儲存失敗。')}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{if(editing){await mutate({id:editing,title,subject,keywords,description});}else{if(!file)throw Error('請先選擇圖片。');if(file.size>3*1024*1024)throw Error('圖片請控制在 3 MB 以內。');const form=new FormData();form.set('file',file);form.set('title',title);form.set('subject',subject);form.set('keywords',keywords);form.set('description',description);form.set('enabled',String(enabled));const r=await fetch('/api/admin/teaching-images',{method:'POST',body:form}),d=await r.json();if(!r.ok)throw Error(d.error);}reset();await load();setNotice(editing?'圖片說明已更新。':'圖片已上傳；啟用後，AI 會依科目與關鍵字挑選相關參考圖。');}catch(e){setError(e instanceof Error?e.message:'儲存失敗。')}finally{setBusy(false)}}
 const visible=items.filter(i=>(!filter||i.subject===filter)&&(!query||`${i.title} ${i.description} ${i.keywords.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
 return <div className="admin-stack teaching-image-library">
 <section className="hh-card admin-panel"><div className="hh-eyebrow">TEACHING IMAGE LIBRARY</div><h2>教學圖庫</h2><p>上傳講義中的圖，讓 AI 依題意選用。共用教材由總管理員管理；教師可瀏覽。</p><p>這是解題時檢索參考圖，不會直接訓練或改變模型。請使用可提供學生閱讀的教材圖片，並裁掉姓名等個人資料。</p></section>
 <details className="hh-card admin-panel"><summary>內建科學圖模板 · 7 種</summary><div className="image-library-samples"><select className="hh-select" aria-label="預覽圖形模板" value={sample} onChange={e=>setSample(Number(e.target.value))}>{examples.map((x,i)=><option key={x.title} value={i}>{x.title}</option>)}</select><ScienceDiagramView diagram={normalizeScienceDiagram({...examples[sample],type:'generic',confidence:100,caption:'功能示範，非特定題目答案；裝置圖不按比例。'})}/></div></details>
 {error&&<div className="admin-notice danger" role="alert">{error}</div>}{notice&&<div className="admin-notice success" role="status">{notice}</div>}
 {canEdit&&<section className="hh-card admin-panel"><h3>{editing?'編輯圖片說明':'新增講義圖片'}</h3><form onSubmit={save}><fieldset disabled={busy} className="image-library-form">
 {!editing&&<label>選擇圖片（PNG / JPEG / WebP，最多 3 MB）<input key={fileKey} type="file" accept="image/png,image/jpeg,image/webp" required onChange={e=>{setFile(e.target.files?.[0]||null);setError('')}}/></label>}
 {preview&&<img src={preview} alt="上傳預覽" className="image-library-preview"/>}
 <label>圖片標題<input className="hh-input" value={title} maxLength={80} required onChange={e=>setTitle(e.target.value)} placeholder="例如：簡易蒸餾裝置"/></label>
 <label>科目<select className="hh-select" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>關鍵字（用逗號分開）<input className="hh-input" required value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="蒸餾,冷凝管,沸點,分離混合物"/></label>
 <label>適用情境與圖中重點<textarea className="hh-input" rows={4} required maxLength={1500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="說明適用題型、器材配置，以及不適用的情況。AI 會以此判斷是否選用。"/></label>
 {!editing&&<label className="image-library-enable"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>上傳後啟用，允許 AI 選用並向學生顯示</label>}
 <div className="admin-actions"><button className="hh-button-primary" type="submit">{busy?'儲存中…':editing?'儲存說明':'上傳圖片'}</button>{editing&&<button type="button" className="hh-button-secondary" onClick={reset}>取消編輯</button>}</div></fieldset></form></section>}
 <section className="hh-card admin-panel"><div className="image-library-filters"><input className="hh-input" aria-label="搜尋教學圖庫" placeholder="搜尋標題、關鍵字或用途" value={query} onChange={e=>setQuery(e.target.value)}/><select className="hh-select" aria-label="篩選科目" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部科目</option>{subjects.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="hh-button-secondary" onClick={()=>void load()} disabled={busy||loading}>重新整理</button></div><p>{loading?'讀取中…':`${visible.length} 張圖片 · ${items.filter(i=>i.enabled).length} 張啟用（圖庫上限 500 張）`}</p>
 <div className="image-library-grid">{visible.map(item=><article key={item.id}><a href={`/api/teaching-images/${item.id}`} target="_blank" rel="noreferrer" aria-label={`開啟 ${item.title}`}><img loading="lazy" src={`/api/teaching-images/${item.id}`} alt={item.title}/></a><div><small>{subjects.find(s=>s[0]===item.subject)?.[1]} · {item.enabled?'已啟用':'未啟用'}</small><h3>{item.title}</h3><p>{item.description}</p><p className="image-library-keywords">{item.keywords.join(' · ')}</p>{canEdit&&<div className="admin-actions"><button className="hh-button-secondary" disabled={busy} onClick={()=>{setEditing(item.id);setFile(null);setTitle(item.title);setSubject(item.subject);setKeywords(item.keywords.join(', '));setDescription(item.description);setNotice('已載入上方編輯表單。')}}>編輯</button><button className="hh-button-secondary" disabled={busy} onClick={()=>void action({id:item.id,action:'toggle',enabled:!item.enabled})}>{item.enabled?'停用':'啟用'}</button><button className="admin-ghost-button" disabled={busy} onClick={()=>{if(confirm('移除此圖後不再供新的解題選用，既有解題紀錄仍保留圖片。確定移除？'))void action({id:item.id,action:'archive'})}}>移除</button></div>}</div></article>)}</div>{!loading&&!visible.length&&<p className="admin-empty">尚無符合條件的圖片。</p>}</section>
 <style jsx global>{`.image-library-form{border:0;padding:0;margin:0;display:grid;gap:16px}.image-library-form label{display:grid;gap:8px;font-size:13px}.image-library-form textarea{height:auto!important;min-height:110px;padding:12px!important}.image-library-form .image-library-enable{display:flex;align-items:center}.image-library-preview{max-height:260px;max-width:100%;object-fit:contain;background:white;border-radius:10px}.image-library-filters{display:flex;gap:10px;flex-wrap:wrap}.image-library-filters input{flex:1;min-width:180px}.image-library-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.image-library-grid article{border:1px solid var(--border);border-radius:14px;overflow:hidden;min-width:0}.image-library-grid article>a{display:block;background:#fff}.image-library-grid img{display:block;width:100%;height:210px;object-fit:contain}.image-library-grid article>div{padding:16px}.image-library-grid p{font-size:13px;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere}.image-library-grid h3{font-size:16px}.image-library-grid small,.image-library-keywords{color:var(--text-secondary)}.image-library-samples{max-width:600px;margin:16px auto}.image-library-grid .admin-actions{flex-wrap:wrap}.teaching-image-library summary{cursor:pointer;font-weight:700}.teaching-image-library>.admin-panel>p{font-size:13px;line-height:1.8;color:var(--text-secondary)}@media(max-width:760px){.image-library-grid{grid-template-columns:1fr}.image-library-filters>*{width:100%}}`}</style>
 </div>;
}
